---
abstract: 'Use the PPI to dump the structure of a Perl file'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PPI-Dumper
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: 6.48
  Getopt::Std: 0
  PPI: 0
  PPI::Dumper: 0
  Test::More: 0.95
  Test::Output: 0
resources:
  repository: https://github.com/briandfoy/app-ppi-dumper
version: 1.02
